### ISSUE TITLE
Assertion `seqno_released + 1 == it->first || seqno_released == 0' in gcache::GCache::seqno_release

### ISSUE THREAD

**Issue by philip-galera** [codership/galera#166]
When executing the galera.galera_restart_nochanges MTR test in a series with other tests, mysqld twice asserted as follows:

```
mysqld: gcache/src/GCache_seqno.cpp:137: void gcache::GCache::seqno_release(int64_t): Assertion `seqno_released + 1 == it->first || seqno_released == 0' failed.

#3  <signal handler called>
#4  0x00000036570328a5 in raise () from /lib64/libc.so.6
#5  0x0000003657034085 in abort () from /lib64/libc.so.6
#6  0x000000365702ba1e in __assert_fail_base () from /lib64/libc.so.6
#7  0x000000365702bae0 in __assert_fail () from /lib64/libc.so.6
#8  0x00007ff5ee5c5807 in gcache::GCache::seqno_release (this=0x3039760, seqno=2372) at gcache/src/GCache_seqno.cpp:137
#9  0x00007ff5ee6d1239 in galera::ServiceThd::thd_func (arg=0x3039a60) at galera/src/galera_service_thd.cpp:76
#10 0x0000003657807851 in start_thread () from /lib64/libpthread.so.0
#11 0x00000036570e890d in clone () from /lib64/libc.so.6

```

The other thread that is doing something is:

```
Thread 21 (Thread 0x7ff5ec1d5700 (LWP 13375)):
#0  0x000000365780b43c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007ff5ee6d1ee8 in wait (this=0x3039a60) at galerautils/src/gu_lock.hpp:56
#2  galera::ServiceThd::flush (this=0x3039a60) at galera/src/galera_service_thd.cpp:123
#3  0x00007ff5ee6caf79 in galera::Certification::assign_initial_position (this=0x3039ec8, seqno=2372, version=3) at galera/src/certification.cpp:895
#4  0x00007ff5ee7003a8 in galera::ReplicatorSMM::process_conf_change (this=0x3039510, recv_ctx=0x7ff59c0008c0, view_info=..., repl_proto=6, next_state=galera::Replicator::S_SYNCED, seqno_l=<value optimized out>) at galera/src/replicator_smm.cpp:1408
#5  0x00007ff5ee6d730a in galera::GcsActionSource::dispatch (this=0x3039b98, recv_ctx=0x7ff59c0008c0, act=<value optimized out>, exit_loop=<value optimized out>) at galera/src/gcs_action_source.cpp:138
#6  0x00007ff5ee6d76d3 in galera::GcsActionSource::process (this=0x3039b98, recv_ctx=0x7ff59c0008c0, exit_loop=@0x7ff5ec1d457f) at galera/src/gcs_action_source.cpp:180
#7  0x00007ff5ee6f896b in galera::ReplicatorSMM::async_recv (this=0x3039510, recv_ctx=0x7ff59c0008c0) at galera/src/replicator_smm.cpp:354
#8  0x00000000006403ed in wsrep_replication_process (thd=0x7ff59c0008c0) at /home/philips/git/mysql-wsrep/sql/wsrep_thd.cc:309
#9  0x00000000006209d5 in start_wsrep_THD (arg=0x640343) at /home/philips/git/mysql-wsrep/sql/mysqld.cc:5374
#10 0x0000003657807851 in start_thread () from /lib64/libpthread.so.0
#11 0x00000036570e890d in clone () from /lib64/libc.so.6
```

The crash is on the master, even though the test restarts the slave. No SQL is executed on the master while the slave is being restarted.

**Comment by ayurchen** [comment]
Philip, can this be closed?

**Comment by philip-galera** [comment]
Thank you for adding this extra debug output, I will capture it if I observe the bug again.

Since there is no fix for the underlying bug, I say we keep it open until more information becomes available.

**Comment by ayurchen** [comment]
I thought https://github.com/codership/galera/commit/4b76c3806bce9d0b6228c1d6591428aa4328e92e is the fix.

**Comment by philip-galera** [comment]
Oh, sorry I did not notice that. Give me a day to try to force the problem to appear again. If it does not, I will close the ticket.

**Comment by philip-galera** [comment]
This assertion has not been seen since, so closing.b
