### ISSUE TITLE
Thread blocked in LocalOrder waiting for a signal that never comes

### ISSUE THREAD

**Issue by philip-galera** [codership/galera#337]
With the RQG workload from the weekly RQG test , there is a cluster-wide deadlock where an applier thread is blocked waiting for a thread that is in this state:

```
0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f0f792a2824 in gu::Lock::wait (cond=..., this=0x7f0efdf750a0) at galerautils/src/gu_lock.hpp:56
#2  0x00007f0f792aea3e in galera::Monitor<galera::ReplicatorSMM::LocalOrder>::enter (this=this@entry=0x30dde68, obj=...) at galera/src/monitor.hpp:123
#3  0x00007f0f792b0e36 in galera::ReplicatorSMM::cert (this=this@entry=0x30dd320, trx=trx@entry=0x7f0e74067f90) at galera/src/replicator_smm.cpp:1687
#4  0x00007f0f792a7af3 in galera::ReplicatorSMM::cert_and_catch (this=this@entry=0x30dd320, trx=trx@entry=0x7f0e74067f90) at galera/src/replicator_smm.cpp:1785
#5  0x00007f0f792a7cbe in galera::ReplicatorSMM::pre_commit (this=0x30dd320, trx=0x7f0e74067f90, meta=0x609fb58) at galera/src/replicator_smm.cpp:730
#6  0x00007f0f792ba75a in galera_pre_commit (gh=<optimized out>, conn_id=23, trx_handle=<optimized out>, flags=<optimized out>, meta=0x609fb58) at galera/src/wsrep_provider.cpp:513
#7  0x00000000008dc16b in wsrep_run_wsrep_commit (thd=0x609de50, hton=0x3104850, all=true) at /home/jenkins/workspace/weekly-rqg/mysql-wsrep/sql/wsrep_hton.cc:450
#8  0x00000000008dacb8 in wsrep_prepare (hton=0x3104850, thd=0x609de50, all=true) at /home/jenkins/workspace/weekly-rqg/mysql-wsrep/sql/wsrep_hton.cc:175
#9  0x000000000064e650 in ha_prepare_low (thd=0x609de50, all=true) at /home/jenkins/workspace/weekly-rqg/mysql-wsrep/sql/handler.cc:2151
#10 0x0000000000723a9f in TC_LOG_DUMMY::prepare (this=0x1813728 <tc_log_dummy>, thd=0x609de50, all=true) at /home/jenkins/workspace/weekly-rqg/mysql-wsrep/sql/log.h:137
#11 0x000000000064cb2b in ha_commit_trans (thd=0x609de50, all=true, ignore_global_read_lock=false) at /home/jenkins/workspace/weekly-rqg/mysql-wsrep/sql/handler.cc:1458
#12 0x00000000008b6f27 in trans_commit (thd=0x609de50) at /home/jenkins/workspace/weekly-rqg/mysql-wsrep/sql/transaction.cc:246
#13 0x000000000088a5ba in fix_autocommit (self=0x182ab80 <Sys_autocommit>, thd=0x609de50, type=OPT_SESSION) at /home/jenkins/workspace/weekly-rqg/mysql-wsrep/sql/sys_vars.cc:3237
#14 0x0000000000737f0a in sys_var::update (this=0x182ab80 <Sys_autocommit>, thd=0x609de50, var=0x7f0e94004c68) at /home/jenkins/workspace/weekly-rqg/mysql-wsrep/sql/set_var.cc:198
#15 0x0000000000738fa8 in set_var::update (this=0x7f0e94004c68, thd=0x609de50) at /home/jenkins/workspace/weekly-rqg/mysql-wsrep/sql/set_var.cc:670
#16 0x0000000000738b81 in sql_set_variables (thd=0x609de50, var_list=0x60a0aa0) at /home/jenkins/workspace/weekly-rqg/mysql-wsrep/sql/set_var.cc:573
#17 0x00000000007ea3cc in mysql_execute_command (thd=0x609de50) at /home/jenkins/workspace/weekly-rqg/mysql-wsrep/sql/sql_parse.cc:4083
#18 0x00000000007f2b55 in mysql_parse (thd=0x609de50, rawbuf=0x7f0e94004b10 "SET AUTOCOMMIT=ON", length=17, parser_state=0x7f0efdf78290) at /home/jenkins/workspace/weekly-rqg/mysql-wsrep/sql/sql_pa$
#19 0x00000000007f207d in wsrep_mysql_parse (thd=0x609de50, rawbuf=0x7f0e94004b10 "SET AUTOCOMMIT=ON", length=17, parser_state=0x7f0efdf78290) at /home/jenkins/workspace/weekly-rqg/mysql-wsrep/sql/$
#20 0x00000000007e3a91 in dispatch_command (command=COM_QUERY, thd=0x609de50, packet=0x60a17a1 "SET AUTOCOMMIT=ON", packet_length=17) at /home/jenkins/workspace/weekly-rqg/mysql-wsrep/sql/sql_parse$
#21 0x00000000007e2577 in do_command (thd=0x609de50) at /home/jenkins/workspace/weekly-rqg/mysql-wsrep/sql/sql_parse.cc:1118
#22 0x00000000007ab612 in do_handle_one_connection (thd_arg=0x609de50) at /home/jenkins/workspace/weekly-rqg/mysql-wsrep/sql/sql_connect.cc:1007
#23 0x00000000007ab136 in handle_one_connection (arg=0x609de50) at /home/jenkins/workspace/weekly-rqg/mysql-wsrep/sql/sql_connect.cc:916
#24 0x00007f0f7a19d182 in start_thread (arg=0x7f0efdf79700) at pthread_create.c:312
#25 0x00007f0f796aa47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

threads:  https://gist.github.com/philip-galera/ed6ca7bbc8007e95515e
innodb status: https://gist.github.com/philip-galera/1e4c7a572365deefd890

**Comment by philip-galera** [comment]
RQG test:

```
cd $HOME/cache/randgen_gc

./runall-new.pl \
    --basedir=$WORKSPACE/mysql-wsrep \
    --grammar=./conf/galera/galera_stress-56-noddl.yy \
    --gendata=./conf/galera/galera_stress-56.zz \
    --galera=mmms \
    --mysqld=--wsrep-provider=$WORKSPACE/galera/libgalera_smm.so \
    --mysqld=--performance-schema=OFF \
    --threads=64 \
    --duration=86400 \
    --rows=100000 \
    --mysqld=--innodb_buffer_pool_size=1G \
    --queries=2147483647 \
    --mysqld=--innodb_flush_log_at_trx_commit=2 \
    --mysqld=--wsrep_slave_threads=16 \
    --mysqld=--innodb_lock_wait_timeout=5
```
