### ISSUE TITLE
After package update on Ubuntu 14.04, "mysqld 10.0.21-MariaDB-1~trusty-wsrep" crashes

### ISSUE THREAD

**Issue by nirbhayc** [codership/galera#366]
Originally filed as : https://mariadb.atlassian.net/browse/MDEV-8820

A user reports a crash with following stack trace, witnessed after upgrading the galera server.

```
#0  0x00007ffff6391cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff63950d8 in __GI_abort () at abort.c:89
#2  0x00007ffff4be7547 in gu_abort () from /usr/lib/galera/libgalera_smm.so
#3  0x00007ffff4cf3a9b in gcs_core_recv(gcs_core*, gcs_act_rcvd*, long long) () from /usr/lib/galera/libgalera_smm.so
#4  0x00007ffff4cf7646 in ?? () from /usr/lib/galera/libgalera_smm.so
#5  0x00007ffff6d32182 in start_thread (arg=0x7fffe87ff700) at pthread_create.c:312
#6  0x00007ffff645547d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:11
```

**Comment by ayurchen** [comment]
Nirbhay, the original bug report is closed, what shall we make out of it? Also, we'll need an error log from that.

From the error log present in the original bug report the node does not crash, it **aborts** in a controlled manner due to inability to receive state transfer. It is not clear why the core is dumped, but it is likely due to specific OS settings with the user. Normally core dump is prevented.

**Comment by nirbhayc** [comment]
I closed the original one as duplicate after reporting it here, thinking it a galera issue.
Anyway, I have asked the bug reporter for donor error logs to get a complete picture.
