### ISSUE TITLE
Hang when shutting down at "Closing slave action queue."

### ISSUE THREAD

**Issue by fredsted** [codership/galera#456]
Sometimes we've experienced nodes who got disconnected and gets stuck with the wsrep_local_state = 1 (Establishing). There's 4 nodes running mysqld 10.0.29-MariaDB-1~trusty-wsrep on Ubuntu 14.04.

Trying get the node up again by restarting the server, the shutdown seems hang at "Closing slave action queue" for hours.

Looking at the source[1], a bug seems to have been created at #113, but that issue seems unrelated to this untrained eye.

I have attached a log[2] of the shutdown.

I've run into this issue occasionally, and it would be nice if this was handled in some way to avoid the anxiety of `kill -9`'ing the process.

[1] https://github.com/codership/galera/blob/7e383f7989e04247f5944beff946823435088e56/gcs/src/gcs.cpp#L1186

[2] [galera-hang.txt](https://github.com/codership/galera/files/835679/galera-hang.txt)

**Comment by ayurchen** [comment]
Unfortunately, provided information is not enough to reproduce the issue.

**Comment by fredsted** [comment]
What do you need?

**Comment by ayurchen** [comment]
Ideally - an MTR test to reproduce the issue.

A stack dump. Then we could determine if it is a Galera-side bug at least.

But my hunch is that it is a MariaDB side and you should report it to the product vendor. ;)

**Comment by asbai** [comment]
I have the same problem, and here is my log:

```
2019-10-19 12:00:22 0 [Note] /usr/sbin/mysqld (initiated by: unknown): Normal shutdown
2019-10-19 12:00:22 0 [Note] WSREP: Shutdown replication
2019-10-19 12:00:22 0 [Note] WSREP: Server status change synced -> disconnecting
2019-10-19 12:00:22 0 [Note] WSREP: wsrep_notify_cmd is not defined, skipping notification.
2019-10-19 12:00:22 0 [Note] WSREP: Closing send monitor...
2019-10-19 12:00:22 0 [Note] WSREP: Closed send monitor.
2019-10-19 12:00:22 0 [Note] WSREP: gcomm: terminating thread
2019-10-19 12:00:22 0 [Note] WSREP: gcomm: joining thread
2019-10-19 12:00:22 0 [Note] WSREP: gcomm: closing backend
2019-10-19 12:00:25 0 [Note] WSREP: (a7d49850, 'tcp://192.168.143.200:4567') connection to peer d731a2f4 with addr tcp://192.168.143.201:4567 timed out, no messages seen in PT2.5S
2019-10-19 12:00:25 0 [Note] WSREP: (a7d49850, 'tcp://192.168.143.200:4567') turning message relay requesting on, nonlive peers: tcp://192.168.143.201:4567 
2019-10-19 12:00:26 0 [Note] WSREP: (a7d49850, 'tcp://192.168.143.200:4567') reconnecting to d731a2f4 (tcp://192.168.143.201:4567), attempt 0
2019-10-19 12:00:27 0 [Note] WSREP: evs::proto(a7d49850, LEAVING, view_id(REG,a7d49850,2)) suspecting node: d731a2f4
2019-10-19 12:00:27 0 [Note] WSREP: evs::proto(a7d49850, LEAVING, view_id(REG,a7d49850,2)) suspected node without join message, declaring inactive
2019-10-19 12:00:27 0 [Note] WSREP: view(view_id(NON_PRIM,a7d49850,2) memb {
	a7d49850,0
} joined {
} left {
} partitioned {
	d731a2f4,0
})
2019-10-19 12:00:27 0 [Note] WSREP: PC protocol downgrade 1 -> 0
2019-10-19 12:00:27 0 [Note] WSREP: view((empty))
2019-10-19 12:00:27 0 [Note] WSREP: gcomm: closed
2019-10-19 12:00:27 0 [Note] WSREP: New COMPONENT: primary = no, bootstrap = no, my_idx = 0, memb_num = 1
2019-10-19 12:00:27 0 [Note] WSREP: Writing down CC checksum: d40722d7 1d9fc92a a79be5e3 da4e6a9b at offset 120
2019-10-19 12:00:27 0 [Note] WSREP: Flow-control interval: [253, 256]
2019-10-19 12:00:27 0 [Note] WSREP: Trying to continue unpaused monitor
2019-10-19 12:00:27 0 [Note] WSREP: Received NON-PRIMARY.
2019-10-19 12:00:27 0 [Note] WSREP: Shifting SYNCED -> OPEN (TO: 398)
2019-10-19 12:00:27 0 [Note] WSREP: Received self-leave message.
2019-10-19 12:00:27 0 [Note] WSREP: Writing down CC checksum: b8ffac2a 682e0605 b47dccc3 84924fc1 at offset 64
2019-10-19 12:00:27 0 [Note] WSREP: Flow-control interval: [0, 0]
2019-10-19 12:00:27 0 [Note] WSREP: Trying to continue unpaused monitor
2019-10-19 12:00:27 0 [Note] WSREP: Received SELF-LEAVE. Closing connection.
2019-10-19 12:00:27 0 [Note] WSREP: Shifting OPEN -> CLOSED (TO: -1)
2019-10-19 12:00:27 0 [Note] WSREP: RECV thread exiting 0: Success
2019-10-19 12:00:27 0 [Note] WSREP: recv_thread() joined.
2019-10-19 12:00:27 0 [Note] WSREP: Closing replication queue.
2019-10-19 12:00:27 0 [Note] WSREP: Closing slave action queue.
2019-10-19 12:00:27 23 [Note] WSREP: ####### processing CC -1, local, ordered
2019-10-19 12:00:27 23 [Note] WSREP: ####### drain monitors upto 398
2019-10-19 12:00:27 23 [Note] WSREP: ####### My UUID: a7d49850-f267-11e9-a686-c29ad84d2767
2019-10-19 12:00:27 23 [Note] WSREP: ####### ST not required
2019-10-19 12:00:27 23 [Note] WSREP: ================================================
View:
  id: d4e10b2c-f17f-11e9-8fee-ce97cf6630f2:-1
  status: non-primary
  protocol_version: 4
  capabilities: MULTI-MASTER, CERTIFICATION, PARALLEL_APPLYING, REPLAY, ISOLATION, PAUSE, CAUSAL_READ, INCREMENTAL_WS, UNORDERED, PREORDERED, STREAMING, NBO
  final: no
  own_index: 0
  members(1):
	0: a7d49850-f267-11e9-a686-c29ad84d2767, DB-0
=================================================
2019-10-19 12:00:27 23 [Note] WSREP: Non-primary view
2019-10-19 12:00:27 23 [Note] WSREP: wsrep_notify_cmd is not defined, skipping notification.
2019-10-19 12:00:27 23 [Note] WSREP: ####### processing CC -1, local, ordered
2019-10-19 12:00:27 23 [Note] WSREP: ####### drain monitors upto 398
2019-10-19 12:00:27 23 [Note] WSREP: ####### My UUID: a7d49850-f267-11e9-a686-c29ad84d2767
2019-10-19 12:00:27 23 [Note] WSREP: ####### ST not required
2019-10-19 12:00:27 23 [Note] WSREP: ================================================
View:
  id: d4e10b2c-f17f-11e9-8fee-ce97cf6630f2:-1
  status: non-primary
  protocol_version: 4
  capabilities: MULTI-MASTER, CERTIFICATION, PARALLEL_APPLYING, REPLAY, ISOLATION, PAUSE, CAUSAL_READ, INCREMENTAL_WS, UNORDERED, PREORDERED, STREAMING, NBO
  final: yes
  own_index: -1
  members(0):
=================================================
2019-10-19 12:00:27 23 [Note] WSREP: Non-primary view
2019-10-19 12:00:27 23 [Note] WSREP: Server status change disconnecting -> disconnected
2019-10-19 12:00:27 23 [Note] WSREP: wsrep_notify_cmd is not defined, skipping notification.
2019-10-19 12:00:27 23 [Note] WSREP: wsrep_notify_cmd is not defined, skipping notification.
2019-10-19 12:00:27 24 [Note] WSREP: Applier thread exiting ret: 6 thd: 24
2019-10-19 12:00:27 24 [Warning] Aborted connection 24 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 28 [Note] WSREP: Applier thread exiting ret: 6 thd: 28
2019-10-19 12:00:27 28 [Warning] Aborted connection 28 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 30 [Note] WSREP: Applier thread exiting ret: 6 thd: 30
2019-10-19 12:00:27 30 [Warning] Aborted connection 30 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 31 [Note] WSREP: Applier thread exiting ret: 6 thd: 31
2019-10-19 12:00:27 31 [Warning] Aborted connection 31 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 16 [Note] WSREP: Applier thread exiting ret: 6 thd: 16
2019-10-19 12:00:27 16 [Warning] Aborted connection 16 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 35 [Note] WSREP: Applier thread exiting ret: 6 thd: 35
2019-10-19 12:00:27 35 [Warning] Aborted connection 35 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 37 [Note] WSREP: Applier thread exiting ret: 6 thd: 37
2019-10-19 12:00:27 37 [Warning] Aborted connection 37 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 19 [Note] WSREP: Applier thread exiting ret: 6 thd: 19
2019-10-19 12:00:27 19 [Warning] Aborted connection 19 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 13 [Note] WSREP: Applier thread exiting ret: 6 thd: 13
2019-10-19 12:00:27 13 [Warning] Aborted connection 13 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 15 [Note] WSREP: Applier thread exiting ret: 6 thd: 15
2019-10-19 12:00:27 15 [Warning] Aborted connection 15 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 20 [Note] WSREP: Applier thread exiting ret: 6 thd: 20
2019-10-19 12:00:27 20 [Warning] Aborted connection 20 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 26 [Note] WSREP: Applier thread exiting ret: 6 thd: 26
2019-10-19 12:00:27 26 [Warning] Aborted connection 26 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 32 [Note] WSREP: Applier thread exiting ret: 6 thd: 32
2019-10-19 12:00:27 32 [Warning] Aborted connection 32 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 27 [Note] WSREP: Applier thread exiting ret: 6 thd: 27
2019-10-19 12:00:27 27 [Warning] Aborted connection 27 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 33 [Note] WSREP: Applier thread exiting ret: 6 thd: 33
2019-10-19 12:00:27 33 [Warning] Aborted connection 33 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 25 [Note] WSREP: Applier thread exiting ret: 6 thd: 25
2019-10-19 12:00:27 25 [Warning] Aborted connection 25 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 36 [Note] WSREP: Applier thread exiting ret: 6 thd: 36
2019-10-19 12:00:27 36 [Warning] Aborted connection 36 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 38 [Note] WSREP: Applier thread exiting ret: 6 thd: 38
2019-10-19 12:00:27 38 [Warning] Aborted connection 38 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 17 [Note] WSREP: Applier thread exiting ret: 6 thd: 17
2019-10-19 12:00:27 17 [Warning] Aborted connection 17 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 12 [Note] WSREP: Applier thread exiting ret: 6 thd: 12
2019-10-19 12:00:27 12 [Warning] Aborted connection 12 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 18 [Note] WSREP: Applier thread exiting ret: 6 thd: 18
2019-10-19 12:00:27 18 [Warning] Aborted connection 18 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 29 [Note] WSREP: Applier thread exiting ret: 6 thd: 29
2019-10-19 12:00:27 29 [Warning] Aborted connection 29 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 10 [Note] WSREP: Applier thread exiting ret: 6 thd: 10
2019-10-19 12:00:27 40 [Note] WSREP: Applier thread exiting ret: 6 thd: 40
2019-10-19 12:00:27 10 [Warning] Aborted connection 10 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 40 [Warning] Aborted connection 40 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 14 [Note] WSREP: Applier thread exiting ret: 6 thd: 14
2019-10-19 12:00:27 14 [Warning] Aborted connection 14 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 11 [Note] WSREP: Applier thread exiting ret: 6 thd: 11
2019-10-19 12:00:27 11 [Warning] Aborted connection 11 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 39 [Note] WSREP: Applier thread exiting ret: 6 thd: 39
2019-10-19 12:00:27 39 [Warning] Aborted connection 39 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 21 [Note] WSREP: Applier thread exiting ret: 6 thd: 21
2019-10-19 12:00:27 21 [Warning] Aborted connection 21 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 23 [Note] WSREP: Applier thread exiting ret: 0 thd: 23
2019-10-19 12:00:27 23 [Warning] Aborted connection 23 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 0 [Note] WSREP: killing local connection: 71
2019-10-19 12:00:27 22 [Note] WSREP: Applier thread exiting ret: 6 thd: 22
2019-10-19 12:00:27 22 [Warning] Aborted connection 22 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 34 [Note] WSREP: Applier thread exiting ret: 6 thd: 34
2019-10-19 12:00:27 34 [Warning] Aborted connection 34 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
2019-10-19 12:00:27 1 [Note] WSREP: Applier thread exiting ret: 6 thd: 1
2019-10-19 12:00:27 1 [Warning] Aborted connection 1 to db: 'unconnected' user: 'unauthenticated' host: '' (This connection closed normally without authentication)
```

It is infinite until I issued a `killall -9 mysqld`. And even `mysqld --version` may issue a segfault during the hanging state.
```
root@DB-0:~# mysqld --version
mysqld  Ver 10.4.8-MariaDB-1:10.4.8+maria~bionic for debian-linux-gnu on x86_64 (mariadb.org binary distribution)
Segmentation fault (core dumped)
```

**Comment by asbai** [comment]
I Start gdb, attach to the hanging process, and do a backtrace:
```
(gdb) bt
#0  0x00007f318592a9d0 in __GI___nanosleep (requested_time=requested_time@entry=0x7ffc79ea2400, remaining=remaining@entry=0x7ffc79ea2400)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007f318592a8aa in __sleep (seconds=0) at ../sysdeps/posix/sleep.c:55
#2  0x000055d18fe341f2 in wsrep_close_client_connections(char, THD*) ()
#3  0x000055d18fe38361 in wsrep_shutdown_replication() ()
#4  0x000055d18fc05ab5 in mysqld_main(int, char**) ()
#5  0x00007f3185867b97 in __libc_start_main (main=0x55d18fbdfac0 <main>, argc=3, argv=0x7ffc79ea3338, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7ffc79ea3328) at ../csu/libc-start.c:310
#6  0x000055d18fbf7f6a in _start ()
```

**Comment by MehdinMasinovic** [comment]
Has anyone found the root cause to this issue?

I have experienced the same problem in our three-node Galera Cluster (MariaDB 10.6.8, Galera 4-26.4.11, Centos 7.8):

```
2022-09-14 12:38:28 0 [Note] /usr/sbin/mariadbd (initiated by: unknown): Normal shutdown
2022-09-14 12:38:28 0 [Note] WSREP: Shutdown replication
2022-09-14 12:38:28 0 [Note] WSREP: Server status change synced -> disconnecting
2022-09-14 12:38:28 0 [Note] WSREP: wsrep_notify_cmd is not defined, skipping notification.
2022-09-14 12:38:28 0 [Note] WSREP: Closing send monitor...
2022-09-14 12:38:28 0 [Note] WSREP: Closed send monitor.
2022-09-14 12:38:28 0 [Note] WSREP: gcomm: terminating thread
2022-09-14 12:38:28 0 [Note] WSREP: gcomm: joining thread
2022-09-14 12:38:28 0 [Note] WSREP: gcomm: closing backend
2022-09-14 12:38:28 0 [Note] WSREP: view(view_id(NON_PRIM,dc8d7a84-a820,10) memb {
	df21fb70-b102,0
} joined {
} left {
} partitioned {
	dc8d7a84-a820,0
	e6965b60-830b,0
})
2022-09-14 12:38:28 0 [Note] WSREP: PC protocol downgrade 1 -> 0
2022-09-14 12:38:28 0 [Note] WSREP: view((empty))
2022-09-14 12:38:28 0 [Note] WSREP: gcomm: closed
2022-09-14 12:38:28 0 [Note] WSREP: New COMPONENT: primary = no, bootstrap = no, my_idx = 0, memb_num = 1
2022-09-14 12:38:28 0 [Note] WSREP: Flow-control interval: [16, 16]
2022-09-14 12:38:28 0 [Note] WSREP: Received NON-PRIMARY.
2022-09-14 12:38:28 0 [Note] WSREP: Shifting SYNCED -> OPEN (TO: 6125)
2022-09-14 12:38:28 0 [Note] WSREP: New SELF-LEAVE.
2022-09-14 12:38:28 0 [Note] WSREP: Flow-control interval: [0, 0]
2022-09-14 12:38:28 0 [Note] WSREP: Received SELF-LEAVE. Closing connection.
2022-09-14 12:38:28 0 [Note] WSREP: Shifting OPEN -> CLOSED (TO: 6125)
2022-09-14 12:38:28 0 [Note] WSREP: RECV thread exiting 0: Success
2022-09-14 12:38:28 0 [Note] WSREP: recv_thread() joined.
2022-09-14 12:38:28 0 [Note] WSREP: Closing replication queue.
2022-09-14 12:38:28 0 [Note] WSREP: Closing slave action queue.
2022-09-14 13:04:45 0 [Note] WSREP: Loading provider /usr/lib64/galera-4/libgalera_smm.so initial position: 6957351b-1fa8-11ed-97ea-4369705cab87:6115
2022-09-14 13:04:45 0 [Note] WSREP: wsrep_load(): loading provider library '/usr/lib64/galera-4/libgalera_smm.so'
```

The journald log of the timestamp:

```
Sep 14 12:35:04 hadb1fra2 postfix/cleanup[28402]: B388E39D4: message-id=<20220914103504.B388E39D4@hadb1fra2.localdomain>
Sep 14 12:35:04 hadb1fra2 postfix/qmgr[1648]: B388E39D4: from=<root@hadb1fra2.localdomain>, size=896, nrcpt=1 (queue active)
Sep 14 12:35:04 hadb1fra2 postfix/local[28406]: B388E39D4: to=<root@hadb1fra2.localdomain>, orig_to=<root>, relay=local, delay=3.3, delays=3.2/0.02/0/0.15, dsn=2.0.0, status=sent (delivere
Sep 14 12:35:04 hadb1fra2 postfix/qmgr[1648]: B388E39D4: removed
Sep 14 12:38:28 hadb1fra2 polkitd[912]: Registered Authentication Agent for unix-process:28597:224782834 (system bus name :1.26426 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object pa
Sep 14 12:38:28 hadb1fra2 systemd[1]: Stopping MariaDB 10.6.8 database server...
Sep 14 12:40:01 hadb1fra2 systemd[1]: Started Session 13154 of user root.
Sep 14 12:40:01 hadb1fra2 CROND[28698]: (root) CMD (/usr/lib64/sa/sa1 1 1)
Sep 14 12:40:01 hadb1fra2 systemd[1]: Started Session 13155 of user root.
```

As noted by @fredsted, we had to pkill the PID, after which a restart would work again.

**Comment by itstin** [comment]
I am experiencing the same issue as the previous user. The error persists from version 10.6.18 to 10.6.19. However, I have noticed that it is not necessary to send a kill signal to the actual mysqld process to close it manually. Instead, closing all connections (literally requires restarting maxscale service), including any open MySQL shell sessions, will suffice. The mysqld session will not close until mysql shell session is terminated with the exit; command (if opened in another window). This issue was tested using local Docker image.
I would love some info on what actually happens here and if there is a way to mitigate this issue, thanks in advance.

**Comment by ayurchen** [comment]
It looks like some local connection blocks appliers in the latter case. SHOW FULL PROCESSLIST and a stacktrace for all threads would be invaluable. Or the way to reproduce.
