### ISSUE TITLE
handle_fatal_signal (sig=6) in galera::KeySetOut::KeyPart::release | galera/src/key_set.hpp:595

### ISSUE THREAD

**Issue by rameshvs02** [codership/galera#508]
Getting sig 6 assertion when we test replication with galera cluster.

GDB info
```
#0  __pthread_kill (threadid=<optimized out>, signo=6) at ../sysdeps/unix/sysv/linux/pthread_kill.c:62
#1  0x00000000007b9815 in handle_fatal_signal (sig=6) at /home/galera/mysql-wsrep-5.7.21-25.14/sql/signal_handler.cc:220
#2  <signal handler called>
#3  0x00007f3d56aca428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#4  0x00007f3d56acc02a in __GI_abort () at abort.c:89
#5  0x00007f3d56b0c7ea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7f3d56c25ed8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#6  0x00007f3d56b1537a in malloc_printerr (ar_ptr=<optimized out>, ptr=<optimized out>, str=0x7f3d56c22caf "free(): invalid pointer", action=3) at malloc.c:5006
#7  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3867
#8  0x00007f3d56b1953c in __GI___libc_free (mem=<optimized out>) at malloc.c:2968
#9  0x00007f3d4c8fb85b in galera::KeySetOut::KeyPart::release (this=0x7f3d3c08ffc0, this=0x7f3d3c08ffc0) at galera/src/key_set.hpp:595
#10 galera::KeySetOut::KeyPart::~KeyPart (this=0x7f3d3c08ffc0, __in_chrg=<optimized out>) at galera/src/key_set.hpp:600
#11 std::__copy_move<false, false, std::random_access_iterator_tag>::__copy_m<galera::KeySetOut::KeyPart*, galera::KeySetOut::KeyPart*> (__result=0x7f3cc4019c40, __last=<optimized out>, __first=0x7f3cc4019d88) at /usr/include/c++/5/bits/stl_algobase.h:340
#12 std::__copy_move_a<false, galera::KeySetOut::KeyPart*, galera::KeySetOut::KeyPart*> (__result=<optimized out>, __last=<optimized out>, __first=<optimized out>) at /usr/include/c++/5/bits/stl_algobase.h:402
#13 std::__copy_move_a2<false, __gnu_cxx::__normal_iterator<galera::KeySetOut::KeyPart*, std::vector<galera::KeySetOut::KeyPart, gu::ReservedAllocator<galera::KeySetOut::KeyPart, 5, false> > >, __gnu_cxx::__normal_iterator<galera::KeySetOut::KeyPart*, std::vector<galera::KeySetOut::KeyPart, gu::ReservedAllocator<galera::KeySetOut::KeyPart, 5, false> > > > (__result=..., __last=..., __first=...) at /usr/include/c++/5/bits/stl_algobase.h:438
#14 std::copy<__gnu_cxx::__normal_iterator<galera::KeySetOut::KeyPart*, std::vector<galera::KeySetOut::KeyPart, gu::ReservedAllocator<galera::KeySetOut::KeyPart, 5, false> > >, __gnu_cxx::__normal_iterator<galera::KeySetOut::KeyPart*, std::vector<galera::KeySetOut::KeyPart, gu::ReservedAllocator<galera::KeySetOut::KeyPart, 5, false> > > > (__result=..., __last=..., __first=...) at /usr/include/c++/5/bits/stl_algobase.h:472
#15 galera::KeySetOut::append (this=this@entry=0x7f3cc4019898, kd=...) at galera/src/key_set.cpp:408
#16 0x00007f3d4c9723ea in galera::WriteSetOut::append_key (k=..., this=<optimized out>) at galera/src/write_set_ng.hpp:521
#17 galera::TrxHandle::append_key (key=..., this=0x7f3cc4019560) at galera/src/trx_handle.hpp:377
#18 galera_append_key (gh=<optimized out>, trx_handle=<optimized out>, keys=<optimized out>, keys_num=1, key_type=WSREP_KEY_EXCLUSIVE, copy=true) at galera/src/wsrep_provider.cpp:577
#19 0x0000000000f061c5 in wsrep_append_key (thd=thd@entry=0x7f3cc40008c0, key=key@entry=0x7f3d3c090d80 "", key_len=<optimized out>, shared=shared@entry=false, table=<optimized out>, table_share=<optimized out>, table_share=<optimized out>, trx=<optimized out>) at /home/galera/mysql-wsrep-5.7.21-25.14/storage/innobase/handler/ha_innodb.cc:10635
#20 0x0000000000f0f085 in ha_innobase::wsrep_append_keys (this=this@entry=0x7f3cc401c130, thd=0x7f3cc40008c0, shared=shared@entry=false, record0=record0@entry=0x7f3cc401c778 "", record1=record1@entry=0x7f3cc401c540 "") at /home/galera/mysql-wsrep-5.7.21-25.14/storage/innobase/handler/ha_innodb.cc:10757
#21 0x0000000000f19fb5 in ha_innobase::update_row (this=0x7f3cc401c130, old_row=0x7f3cc401c778 "", new_row=0x7f3cc401c540 "") at /home/galera/mysql-wsrep-5.7.21-25.14/storage/innobase/handler/ha_innodb.cc:9000
#22 0x000000000081dbd2 in handler::ha_update_row (this=0x7f3cc401c130, old_data=0x7f3cc401c778 "", new_data=0x7f3cc401c540 "") at /home/galera/mysql-wsrep-5.7.21-25.14/sql/handler.cc:8160
#23 0x0000000000ecc83f in Rpl_info_table::do_flush_info (this=0x31bc890, force=<optimized out>) at /home/galera/mysql-wsrep-5.7.21-25.14/sql/rpl_info_table.cc:225
#24 0x0000000000eb6509 in Rpl_info_handler::flush_info (force=false, this=<optimized out>) at /home/galera/mysql-wsrep-5.7.21-25.14/sql/rpl_info_handler.h:94
#25 Master_info::flush_info (this=this@entry=0x3200f20, force=force@entry=false) at /home/galera/mysql-wsrep-5.7.21-25.14/sql/rpl_mi.cc:263
#26 0x0000000000ea0b7d in flush_master_info (mi=mi@entry=0x3200f20, force=force@entry=false) at /home/galera/mysql-wsrep-5.7.21-25.14/sql/rpl_slave.cc:1448
#27 0x0000000000eaca5a in handle_slave_io (arg=arg@entry=0x3200f20) at /home/galera/mysql-wsrep-5.7.21-25.14/sql/rpl_slave.cc:6007
#28 0x0000000001202864 in pfs_spawn_thread (arg=0x7f3cd0025f70) at /home/galera/mysql-wsrep-5.7.21-25.14/storage/perfschema/pfs.cc:2190
#29 0x00007f3d57f4d6ba in start_thread (arg=0x7f3d3c093700) at pthread_create.c:333
#30 0x00007f3d56b9c41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Testcase
```
** attached cnf files
mkdir -p /dev/shm/qa/1001/logs

/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysqld --no-defaults --initialize-insecure --basedir=/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64 --datadir=/dev/shm/qa/1001/node1

/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysqld --defaults-file=/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/n1.cnf &

/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysqld --no-defaults --initialize-insecure --basedir=/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64 --datadir=/dev/shm/qa/1001/node2
/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysqld --defaults-file=/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/n2.cnf &

/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysqld --no-defaults --initialize-insecure --basedir=/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64 --datadir=/dev/shm/qa/1001/node3
/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysqld --defaults-file=/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/n3.cnf &

/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysqld --no-defaults --initialize-insecure --basedir=/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64 --datadir=/dev/shm/qa/1001/psnode1

/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysqld --defaults-file=/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/ps1.cnf &

/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysql -uroot --socket=/tmp/n1.sock -e"FLUSH LOGS"
/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysql -uroot --socket=/tmp/n1.sock -Bse 'show master logs'
/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysql -uroot --socket=/tmp/n1.sock -Bse 'select @@port'

/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysql -uroot --socket=/tmp/ms1.sock -e"CHANGE MASTER TO MASTER_HOST='127.0.0.1', MASTER_PORT=21100, MASTER_USER='root', MASTER_AUTO_POSITION=1 ;START SLAVE;"


/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysql -uroot --socket=/tmp/ms1.sock -e"FLUSH LOGS"
/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysql -uroot --socket=/tmp/ms1.sock -Bse 'show master logs'

/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysql -uroot --socket=/tmp/ms1.sock -Bse 'select @@port'


/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysql -uroot --socket=/tmp/n1.sock -e"CHANGE MASTER TO MASTER_HOST='127.0.0.1', MASTER_PORT=21101, MASTER_USER='root', MASTER_AUTO_POSITION=1 ;START SLAVE;"

*** check replication on pxc and ps

/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysql -uroot --socket=/tmp/n2.sock -e 'drop database if exists sbtest_pxc_db;create database sbtest_pxc_db;'
/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysql -uroot --socket=/tmp/ms1.sock -e 'drop database if exists sbtest_ps_db;create database sbtest_ps_db;'

sysbench /usr/share/sysbench/oltp_insert.lua --table-size=5000 --tables=16 --mysql-db=sbtest_ps_db --mysql-user=root --threads=16 --db-driver=mysql --mysql-socket=/tmp/ms1.sock prepare

sysbench /usr/share/sysbench/oltp_insert.lua --table-size=5000 --tables=16 --mysql-db=sbtest_pxc_db --mysql-user=root --threads=16 --db-driver=mysql --mysql-socket=/tmp/n2.sock prepare
 
sysbench /usr/share/sysbench/oltp_read_write.lua --table-size=5000 --tables=16 --mysql-db=sbtest_ps_db --mysql-user=root --threads=16 --time=30 --report-interval=1 --events=1870000000 --db-driver=mysql --db-ps-mode=disable --mysql-socket=/tmp/ms1.sock run

sysbench /usr/share/sysbench/oltp_read_write.lua --table-size=5000 --tables=16 --mysql-db=sbtest_pxc_db --mysql-user=root --threads=16 --time=30 --report-interval=1 --events=1870000000 --db-driver=mysql --db-ps-mode=disable --mysql-socket=/tmp/n1.sock run

*** Initiating master - and - slave shuffle test

/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysql --socket=/tmp/n2.sock -u root -Bse 'select @@port'
 
/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysqladmin --socket=/tmp/n2.sock -u root shutdown

/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysqld --defaults-file=/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/n2.cnf &

/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysql -uroot --socket=/tmp/ms1.sock -e"FLUSH LOGS"
/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysql -uroot --socket=/tmp/ms1.sock -Bse 'show master logs'
/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysql -uroot --socket=/tmp/ms1.sock -Bse 'select @@port'
/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysql -uroot --socket=/tmp/n2.sock -e"CHANGE MASTER TO MASTER_HOST='127.0.0.1', MASTER_PORT=21101, MASTER_USER='root', MASTER_AUTO_POSITION=1 ;START SLAVE;"

/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysql -uroot --socket=/tmp/n2.sock -Bse 'show slave status \G'

/dev/shm/qa/mysql-wsrep-5.7.21-25.14-linux-x86_64/bin/mysql -uroot --socket=/tmp/ms1.sock -e 'drop database if exists sbtest_ps_master;create database sbtest_ps_master;'

sysbench /usr/share/sysbench/oltp_insert.lua --table-size=5000 --tables=16 --mysql-db=sbtest_ps_master --mysql-user=root --threads=16 --db-driver=mysql --mysql-socket=/tmp/ms1.sock prepare

sysbench /usr/share/sysbench/oltp_read_write.lua --table-size=5000 --tables=16 --mysql-db=sbtest_ps_master --mysql-user=root --threads=16 --time=30 --report-interval=1 --events=1870000000 --db-driver=mysql --db-ps-mode=disable --mysql-socket=/tmp/ms1.sock run

sysbench /usr/share/sysbench/oltp_read_write.lua --table-size=5000 --tables=16 --mysql-db=sbtest_pxc_db --mysql-user=root --threads=16 --time=30 --report-interval=1 --events=1870000000 --db-driver=mysql --db-ps-mode=disable --mysql-socket=/tmp/n2.sock run
```

**Comment by rameshvs02** [comment]
[n3.txt](https://github.com/codership/galera/files/2133702/n3.txt)
[n2.txt](https://github.com/codership/galera/files/2133703/n2.txt)
[n1.txt](https://github.com/codership/galera/files/2133704/n1.txt)

**Comment by sjaakola** [comment]
Appears that mysql slave thread is crashing under this test load.
But are you getting this with pxc or galera cluster? Test comment mentions that pxc is used here.

**Comment by rameshvs02** [comment]
The assertion is happening only with Galera cluster. I found this issue while testing PXC cluster hung issue (2 transactions with the same GTID) with upstream.

**Comment by sjaakola** [comment]
ok, thanks for the bug report, and especially for the nice recipe for reproducing the issue, much appreciated

**Comment by alshhrymhmd008** [comment]
Jo

**Comment by alshhrymhmd008** [comment]
Ehjfflggy4
